version: '3.7'
services:
  postgres:
    image: library/postgres:13-alpine
    ports:
       - '5432:5432'
    volumes:
       - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
       - POSTGRES_DB=postgres
       - POSTGRES_PASSWORD=password
       - POSTGRES_USER=app
       - PGDATA=/var/lib/postgresql/data/db-files/
